### ISSUE TITLE
Unite with other Gatsby MDX?

### ISSUE THREAD

**Issue by damassi** [karolis-sh/gatsby-mdx#35]
I've been playing around with your very cool netlify widget and was able to get it to do just what I needed. Thank you for that! Along the way i realized that a lot of the abstractions in this project follow those in https://github.com/ChristopherBiscardi/gatsby-mdx and was wondering if you've seen it? For example, to pluck out the context scope including imports and so on there's [`withMDXScope`](https://github.com/artsy/palette/blob/master/www/src/app/components/Playground.tsx#L16) as used here and a lot of other useful items. Just curious about your thoughts, since y'all even have the same project name :)

**Comment by buz-zard** [comment]
Thanks! 😉

Yes, I've tried Christopher's package before. I had not so great experience with the docs and IE & Edge issues (but that's probably due to my faulty setup). It's a great package and also handles the mdx returned from APIs.

Anyway, I needed more flexible and files oriented (for the netlify-cms) solution.

As for the netlify mdx widget, it doesn't really matter what mdx plugin for gatsby you use, you don't even have to use gatsby. The netlify-cms is a separate SPA, so the widget doesn't enforce any gatsby plugins 😉
